Konzultacije/Konzultacije/Models/Profesor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;

namespace Konzultacije.Models
{
    [Table("Profesor")]
    public class Profesor
    {

        [Key]       
        [Display(Name ="ID Profesora")]
        [Column("id_profesor")]
        public int ProfesorID { get; set; }


        [Column("ime_i_prezime")]
        [Display(Name ="Ime i prezime")]
        [Required(AllowEmptyStrings = false, ErrorMessage ="{0} j eobavezan podatak.")]
        public string Ime_I_Prezime { get; set; }

        [Column("email")]
        [EmailAddress]
        [Display(Name ="Email")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak.")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }


        [Column("lozinka")]
        [Display(Name ="Lozinka")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak.")]
        [StringLength(25, ErrorMessage ="{0} ne moze imati manje od {2} niti vise od {1} slova.", MinimumLength = 7)]
        [DataType(DataType.Password)]
        public string Lozinka { get; set; }


        [Column("aktivacijski_link")]
        [Display(Name ="Aktivacijski link")]
        [DataType(DataType.Url)]
        public string Aktivacijski_Link { get; set; }


        [Column("aktivan")]
        [Display(Name ="Aktivan")]
        public bool Aktivan { get; set; }

        public virtual ICollection<Kolegij_Profesor> Kolegij_Profesors { get; set; }
        public virtual ICollection<Termini> Terminis { get; set; }
        public virtual ICollection<Upit> Upits { get; set; }
            
    }
}

Konzultacije/Konzultacije/Controllers/KolegijController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Konzultacije.Models;

namespace Konzultacije.Controllers
{
    public class KolegijController : Controller
    {
        private BazaDbContext db = new BazaDbContext();

        // GET: Kolegij
        public ActionResult Index()
        {
            return View();
        }

        //moji kontroleri za ispis kolegija
        public ActionResult Popis()
        {
            return View(db.Kolegij.ToList().Where(x => x.Odabran == false).ToList());
            //return View(db.Kolegij.ToList());
        }


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Popis(List<Kolegij> lista)
        //{
        //    if(ModelState.IsValid)
        //    {
        //        db.Entry(lista).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("PopisOdabranih", "Kolegij");
        //    }
        //    return View(db.Kolegij.ToList().Where(x => x.Odabran == false).ToList());

        //}


        public ActionResult PopisOdabranih()
        {          
            
            return View(db.Kolegij.ToList().Where(x => x.Odabran == true).ToList());
        }

        // GET: Kolegij/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kolegij kolegij = db.Kolegij.Find(id);
            if (kolegij == null)
            {
                return HttpNotFound();
            }
            return View(kolegij);
        }

        // GET: Kolegij/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kolegij/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KolegijID,Naziv,Odabran")] Kolegij kolegij)
        {
            if (ModelState.IsValid)
            {
                db.Kolegij.Add(kolegij);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(kolegij);
        }

        // GET: Kolegij/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kolegij kolegij = db.Kolegij.Find(id);
            if (kolegij == null)
            {
                return HttpNotFound();
            }
            return View(kolegij);
        }

        // POST: Kolegij/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KolegijID,Naziv,Odabran")] Kolegij kolegij)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kolegij).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }
            return View(kolegij);
        }

        // GET: Kolegij/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kolegij kolegij = db.Kolegij.Find(id);
            if (kolegij == null)
            {
                return HttpNotFound();
            }
            return View(kolegij);
        }

        // POST: Kolegij/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kolegij kolegij = db.Kolegij.Find(id);
            db.Kolegij.Remove(kolegij);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Konzultacije/Konzultacije/Controllers/ProfesorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Konzultacije.Models;

namespace Konzultacije.Controllers
{
    public class ProfesorController : Controller
    {
        private BazaDbContext db = new BazaDbContext();

        // GET: Profesor
        public ActionResult Popis()
        {
            return View(db.Profesor.ToList());
        }

        //ovo sam ja pisal
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Index(Profesor p)
        {

            return View(p);
        }

        // GET: Profesor/Details/5
        public ActionResult Details(int? id)
        {
            
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Profesor profesor = db.Profesor.Find(id);
            int kolslova = profesor.Lozinka.Count();
            var pass = "";
            for (int i = 0; i < kolslova; i++)
            {
                pass = pass + "•";
            }
            ViewBag.Pass = pass;
            if (id == (int)Session["Profesor"])
            {
                return View(profesor);
            }
            if (profesor == null)
            {
                return HttpNotFound();
            }
            return View(profesor);
        }

        // GET: Profesor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profesor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProfesorID,Ime_I_Prezime,Email,Lozinka,Aktivacijski_Link,Aktivan")] Profesor profesor)
        {
            if (ModelState.IsValid)
            {
                db.Profesor.Add(profesor);
                db.SaveChanges();
                Session["Profesor"] = profesor.ProfesorID;
                return RedirectToAction("Index", "Home" );
            }

            return View(profesor);
        }

        // GET: Profesor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profesor profesor = db.Profesor.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }
            return View(profesor);
        }

        // POST: Profesor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProfesorID,Ime_I_Prezime,Email,Lozinka,Aktivacijski_Link,Aktivan")] Profesor profesor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profesor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(profesor);
        }

        // GET: Profesor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profesor profesor = db.Profesor.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }
            return View(profesor);
        }

        // POST: Profesor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Profesor profesor = db.Profesor.Find(id);
            db.Profesor.Remove(profesor);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Konzultacije/Konzultacije/Controllers/UpitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Konzultacije.Models;

namespace Konzultacije.Controllers
{
    public class UpitController : Controller
    {
        private BazaDbContext db = new BazaDbContext();
        private List<Kolegij> kolegijs = new List<Kolegij>();

        // GET: Upit
        public ActionResult Index(int? id)
        {
            var upit = db.Upit.Include(u => u.Profesor).Include(u => u.Student).Include(u => u.Termini);

            

            if (Session["Profesor"]!=null)
            { 
            Profesor trenutanprof = db.Profesor.Find(id);
            
            return View(upit.ToList().Where(x => x.ProfesorID == trenutanprof.ProfesorID).ToList());
            }

            if (Session["Student"] != null)
            {
                Student trenutanstu = db.Student.Find(id);
                return View(upit.ToList().Where(x => x.StudentID == trenutanstu.StudentID).ToList());
            }
            return View(upit.ToList());
        }

        // GET: Upit/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Upit upit = db.Upit.Find(id);
            if (upit == null)
            {
                return HttpNotFound();
            }
            return View(upit);
        }

        // GET: Upit/Create
        public ActionResult Create()
        {
            int a = (int)Session["Student"];
            Student stu = db.Student.Find(a);
            ViewBag.Student = stu.Ime_I_Prezime;

            
            ViewBag.ProfesorID = new SelectList(db.Profesor, "ProfesorID", "Ime_I_Prezime");
            ViewBag.StudentID = new SelectList(db.Student, "StudentID", "Ime_I_Prezime");
            ViewBag.TerminID = new SelectList(db.Termini, "TerminiID", "KolegijID");
            var listatermina = db.Termini.Include(k => k.Kolegij).Include(k => k.Profesor).ToList();
            foreach(Termini t in listatermina)
            {
                var trenutni = db.Kolegij.Find(t.KolegijID);
                kolegijs.Add(trenutni);
            }
            ViewBag.MojaLista = kolegijs;
            return View();
        }

        // POST: Upit/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UpitID,ProfesorID,TerminID,Naslov,Opis,Odgovor,Odgovoren")] Upit upit)
        {
            int a = (int)Session["Student"];
            Student stu = db.Student.Find(a);
            ViewBag.Student = stu.Ime_I_Prezime;
            
            if (ModelState.IsValid)
            {
                var listatermina = db.Termini.Include(k => k.Kolegij).Include(k => k.Profesor).ToList();
                var kolegij = db.Kolegij.Find(upit.TerminID);
                foreach (Termini t in listatermina)
                {
                    if (t.KolegijID == kolegij.KolegijID)
                    {
                        upit.TerminID = t.TerminiID;
                    }
                   
                }

                upit.StudentID = stu.StudentID;
                db.Upit.Add(upit);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            

            
            ViewBag.ProfesorID = new SelectList(db.Profesor, "ProfesorID", "Ime_I_Prezime", upit.ProfesorID);
            ViewBag.StudentID = new SelectList(db.Student, "StudentID", "Ime_I_Prezime", upit.StudentID);
            ViewBag.TerminID = new SelectList(db.Termini, "TerminiID",  "KolegijID", upit.TerminID);
            return View(upit);
        }

        // GET: Upit/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Upit upit = db.Upit.Find(id);
            if (upit == null)
            {
                return HttpNotFound();
            }

            
            ViewBag.ProfesorID = new SelectList(db.Profesor, "ProfesorID", "Ime_I_Prezime", upit.ProfesorID);
            ViewBag.StudentID = new SelectList(db.Student, "StudentID", "Ime_I_Prezime", upit.StudentID);
            ViewBag.TerminID = new SelectList(db.Termini, "TerminiID", "TerminiID", upit.TerminID);
            return View(upit);
        }

        // POST: Upit/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UpitID,StudentID,ProfesorID,TerminID,Naslov,Opis,Odgovor,Odgovoren")] Upit upit)
        {

            
            if (ModelState.IsValid)
            {
                upit.Odgovoren = true;
                db.Entry(upit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            
            ViewBag.ProfesorID = new SelectList(db.Profesor, "ProfesorID", "Ime_I_Prezime", upit.ProfesorID);
            ViewBag.StudentID = new SelectList(db.Student, "StudentID", "Ime_I_Prezime", upit.StudentID);
            ViewBag.TerminID = new SelectList(db.Termini, "TerminiID", "TerminiID", upit.TerminID);
            return View(upit);
        }

        // GET: Upit/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Upit upit = db.Upit.Find(id);
            if (upit == null)
            {
                return HttpNotFound();
            }
            return View(upit);
        }

        // POST: Upit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Upit upit = db.Upit.Find(id);
            db.Upit.Remove(upit);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Konzultacije/Konzultacije/Views/Profesor/Create.cshtml
@model Konzultacije.Models.Profesor

@{
	ViewBag.Title = "Create";
}

<h2>Registracija profesora</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">

		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Ime_I_Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Ime_I_Prezime, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Ime_I_Prezime, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Lozinka, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Lozinka, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Lozinka, "", new { @class = "text-danger" })
			</div>
		</div>

		@*<div class="form-group">
				@Html.LabelFor(model => model.Aktivacijski_Link, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Aktivacijski_Link, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Aktivacijski_Link, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Aktivan, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					<div class="checkbox">
						@Html.EditorFor(model => model.Aktivan)
						@Html.ValidationMessageFor(model => model.Aktivan, "", new { @class = "text-danger" })
					</div>
				</div>
			</div>*@

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Registriraj" class="btn btn-outline-success" />
			</div>
		</div>
	</div>
}

<div class="col-md-6">

	<div>
		@Html.ActionLink("Natrag na početnu »", "Index", "Home", null, new { @class = "btn btn-info" })
	</div>
</div>


@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Konzultacije/Konzultacije/Views/Profesor/Delete.cshtml
@model Konzultacije.Models.Profesor

@{
    ViewBag.Title = "Brisanje profesora";
}

<h3>@ViewBag.Title @Html.DisplayNameFor(model => model.Ime_I_Prezime)</h3>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime_I_Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime_I_Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lozinka)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lozinka)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aktivacijski_Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aktivacijski_Link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aktivan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aktivan)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

	<div class="form-actions no-color">
		<input type="submit" value="Obrisi profesora" class="btn btn-outline-danger" /> 
		

			<div>
				@Html.ActionLink("Natrag na početnu »", "Index", "Home", null, new { @class = "btn btn-info" })
			</div>
		

	</div>
    }
</div>

Konzultacije/Konzultacije/Views/Profesor/Details.cshtml
@model Konzultacije.Models.Profesor

@{
    ViewBag.Title = "Podaci o profesoru";
}

<h3>@ViewBag.Title @Html.DisplayNameFor(model => model.Ime_I_Prezime)</h3>

<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime_I_Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime_I_Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lozinka)
        </dt>

		<dd>
			@Html.Raw(ViewBag.Pass)
		</dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Aktivacijski_Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aktivacijski_Link)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Aktivan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aktivan)
        </dd>

    </dl>
</div>

	<div class="col-sm-6">
		@Html.ActionLink("Promjeni podatke", "Edit", new { id = Model.ProfesorID }, new { @class = "btn btn-success" })
	</div>
		<br />
	<div class="col-sm-6">
		@Html.ActionLink("Natrag na početnu »", "Index", "Home", null, new { @class = "btn btn-info" })
	</div>

Konzultacije/Konzultacije/Views/Profesor/Index.cshtml
@model Konzultacije.Models.Profesor
@{
	ViewBag.Title = "Pocetna stranica za profesore";
}

<br />
<div class="jumbotron">
	<h2>Dobrodošli profesore @Html.DisplayFor(Model => Model.Ime_I_Prezime)</h2>
	<p class="lead">
		Dobrodošli na stranicu za konzultacije. Ovjde možete odabrati sve opcije za profesore kao što su upis novog termina, 
		pregled svih termina i upita te izmjena osobnih podataka.
	</p>
</div>



<div class="row">
	<div class="col-md-6">
		<h4>Termini konzultacija</h4>
		<p>
			Ovdje se nalazi detaljan pregled i informacije svih objavljenih termina konzultacija te mogućnost filtriranja informacija po upisanom pojmu.
		</p>
		<p>@Html.ActionLink("Termini konzultacija »", "Index", "Termini", null, new { @class = "btn btn-danger" })</p>
		<p>
			Ovdje možete upisati novi termin konzultacije.
		</p>
		<p>@Html.ActionLink("Unos nove konzultacije »", "Create", "Termini", null, new { @class = "btn btn-dark" })</p>
	</div>
	<div class="col-md-6">
		<h4>Upiti od studenata</h4>
		<p>Ovdje možete vidjeti sve upite koje su vam poslali studenti.</p>
		<p>@Html.ActionLink("Popis svih upita »", "Index", "Upit", new { id = Model.ProfesorID}, new { @class = "btn btn-danger" })</p>

		@*<p>Ovdje možete vidjeti popis svih kolegija</p>
		<p>@Html.ActionLink("Popis svih kolegija »", "Popis", "Kolegij", null, new { @class = "btn btn-dark" })</p>

		<p>@Html.ActionLink("Popis", "Popis", "Profesor", null, new { @class = "btn btn-secondary" })</p>*@

	</div>	
</div>

<hr />
<div class="row">
	<div class="col-md-6">
		<h4>Kolegiji</h4>
		<p>Ovdje možete pogledati popis odabranih kolegija</p>
		<p>@Html.ActionLink("Popis odabranih kolegija »", "Index", "Kolegij_profesor", new {ime = Model.Ime_I_Prezime }, new { @class = "btn btn-danger" })</p>

		<p>Ovdje možete odabrati kolegije koje predajete</p>
		<p>@Html.ActionLink("Odabir kolegija »", "Create", "Kolegij_profesor", null, new { @class = "btn btn-dark"})</p>

	</div>
	<div class="col-md-6">
		<h4>Moj profil</h4>
		<p>Ovjde možete vidjeti detalje vašeg profila</p>
		<p></p>
		<p>@Html.ActionLink("Moji podaci »", "Details", "Profesor", new { id = Model.ProfesorID }, new { @class = "btn btn-primary" })</p>
		<p>Ovdje možete izmjeniti svoje osobne podatke.</p>
		<p>@Html.ActionLink("Izmjena podataka »", "Edit", "Profesor", new { id = Model.ProfesorID }, new { @class = "btn btn-warning" })</p>

	</div>
</div>

Konzultacije/Konzultacije/Views/Profesor/Popis.cshtml
@model IEnumerable<Konzultacije.Models.Profesor>
@{
	ViewBag.Title = "Popis";
}

<h2>Popis svih profesora u bazi</h2>


<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Ime_I_Prezime)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Email)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Lozinka)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Aktivacijski_Link)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Aktivan)
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Ime_I_Prezime)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Email)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Lozinka)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Aktivacijski_Link)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Aktivan)
			</td>
			<td>
				@Html.ActionLink("Edit", "Edit", new { id = item.ProfesorID }) |
				@Html.ActionLink("Details", "Details", new { id = item.ProfesorID }) |
				@Html.ActionLink("Delete", "Delete", new { id = item.ProfesorID })
			</td>
		</tr>
	}

</table>